using PvpStats.Types.Match;
using PvpStats.Types.Match.Timeline;
using System;
using System.Net;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Linq;
using System.Reflection;
using System.Text;
using System.Text.Json;
using System.Threading;
using System.Threading.Channels;
using System.Threading.Tasks;

namespace PvpStats.Services.Cloud;

internal sealed class CloudUploadService : IDisposable {
    private readonly Plugin _plugin;
    private readonly FrontlineUploadMapper _mapper;
    private readonly HttpClient _httpClient = new() { Timeout = TimeSpan.FromSeconds(20) };
    private readonly Channel<PendingUpload> _queue = Channel.CreateUnbounded<PendingUpload>(new UnboundedChannelOptions {
        SingleReader = true,
        SingleWriter = false,
    });
    private readonly CancellationTokenSource _shutdown = new();
    private readonly Task _worker;
    private bool _reportedNotReady;

    internal CloudUploadService(Plugin plugin) {
        _plugin = plugin;
        _mapper = new FrontlineUploadMapper(plugin);
        _worker = Task.Run(RunAsync);
    }

    internal async Task<bool> EnqueueAsync(FrontlineMatch match, FrontlineMatchTimeline? timeline = null) {
        if(!_plugin.Configuration.CloudUploadEnabled || !_plugin.Configuration.CloudUploadConsentAccepted) {
            return false;
        }

        try {
            if(!TryGetEndpoint(out _) || !TryGetCredentials(out var credentials)) {
                if(!_reportedNotReady) {
                    _plugin.Log.Warning("Cloud upload is enabled but its endpoint or credentials are not configured.");
                    _reportedNotReady = true;
                }
                return false;
            }

            var envelope = _mapper.Map(match, timeline);
            var body = CloudUploadProtocol.SerializeAndCompress(envelope);
            var sourceMatchId = envelope.Matches[0].SourceMatchId;
            var idempotencyKey = CloudUploadProtocol.CreateIdempotencyKey(credentials.InstallationId, sourceMatchId);
            var existing = _plugin.Storage.GetCloudUploads().FindById(sourceMatchId);
            if(existing?.Status == CloudUploadStatus.Uploaded) {
                return true;
            }
            var record = existing ?? new CloudUploadRecord {
                Id = sourceMatchId,
                Status = CloudUploadStatus.Pending,
                CreatedAt = DateTime.UtcNow,
            };
            record.Status = CloudUploadStatus.Pending;
            record.LastError = null;
            await _plugin.Storage.UpsertCloudUpload(record);
            await _queue.Writer.WriteAsync(new PendingUpload(body, envelope.Client.PluginVersion, envelope.Client.BuildHash, idempotencyKey, sourceMatchId), _shutdown.Token);
            return true;
        } catch(Exception ex) {
            _plugin.Log.Warning(ex, $"Frontline match {match.Id} was not queued for cloud upload.");
            return false;
        }
    }

    internal async Task EnqueueBacklogAsync() {
        if(!_plugin.Configuration.CloudUploadEnabled || !_plugin.Configuration.CloudUploadConsentAccepted) {
            return;
        }

        var pendingIds = _plugin.Storage.GetCloudUploads().Query()
            .Where(record => record.Status != CloudUploadStatus.Uploaded)
            .OrderBy(record => record.CreatedAt)
            .Limit(100)
            .ToList()
            .Select(record => record.Id)
            .ToHashSet(StringComparer.OrdinalIgnoreCase);
        foreach(var match in _plugin.FLCache.Matches.Where(match => pendingIds.Contains(match.Id.ToString()))) {
            await EnqueueAsync(match, _plugin.FLCache.GetTimeline(match) as FrontlineMatchTimeline);
        }
    }

    internal void SetCredentials(string installationId, string accountId, string keyVersion, byte[] secret) {
        _plugin.Configuration.CloudUploadInstallationId = installationId.Trim();
        _plugin.Configuration.CloudUploadAccountId = accountId.Trim();
        _plugin.Configuration.CloudUploadKeyVersion = keyVersion.Trim();
        _plugin.Configuration.CloudUploadProtectedSecret = CloudCredentialProtector.Protect(secret);
        _plugin.Configuration.Save();
        _reportedNotReady = false;
    }

    internal bool IsBound => TryGetCredentials(out _);

    internal async Task<CloudBindingResult> VerifyOwnershipAsync(string code, CancellationToken cancellationToken = default) {
        if(!TryGetCredentials(out var credentials) || !TryGetApiEndpoint(CloudUploadProtocol.OwnershipVerificationPath, out var endpoint)) {
            return new CloudBindingResult(false, "Bind the plugin to your website account first.");
        }
        code = code.Trim();
        if(string.IsNullOrWhiteSpace(code)) {
            return new CloudBindingResult(false, "Enter the ownership verification code generated by the website.");
        }
        try {
            var body = JsonSerializer.SerializeToUtf8Bytes(new { code });
            var pluginVersion = Assembly.GetExecutingAssembly().GetName().Version?.ToString() ?? "0.0.0.0";
            var buildHash = CloudUploadProtocol.GetClientBuildHash();
            var nonce = Guid.NewGuid().ToString();
            var idempotencyKey = $"ownership_{Guid.NewGuid():N}";
            var signed = CloudUploadProtocol.Sign(body, credentials, pluginVersion, buildHash, DateTimeOffset.UtcNow, nonce, idempotencyKey, CloudUploadProtocol.OwnershipVerificationPath);
            using var request = new HttpRequestMessage(HttpMethod.Post, endpoint) { Content = new ByteArrayContent(body) };
            request.Content.Headers.ContentType = new MediaTypeHeaderValue("application/json");
            AddSignedHeaders(request, credentials, signed, nonce, pluginVersion, buildHash, idempotencyKey);
            using var response = await _httpClient.SendAsync(request, HttpCompletionOption.ResponseContentRead, cancellationToken);
            if(response.IsSuccessStatusCode) {
                return new CloudBindingResult(true, "Character ownership verification succeeded. Refresh the website account page.");
            }
            return new CloudBindingResult(false, response.StatusCode == HttpStatusCode.UnprocessableEntity ? "The verification code is invalid, expired, or already used." : "The verification service rejected the request.");
        } catch(OperationCanceledException) when(cancellationToken.IsCancellationRequested) {
            return new CloudBindingResult(false, "Verification was cancelled.");
        } catch(Exception ex) {
            _plugin.Log.Warning(ex, "Character ownership verification failed.");
            return new CloudBindingResult(false, "Unable to reach the verification service. Try again later.");
        }
    }

    internal async Task<CloudBindingResult> BindAsync(string code, CancellationToken cancellationToken = default) {
        if(!TryGetApiEndpoint("/api/v1/plugin/bind", out var endpoint)) {
            return new CloudBindingResult(false, "Enter a valid HTTPS API address first.");
        }
        code = code.Trim();
        if(string.IsNullOrWhiteSpace(code)) {
            return new CloudBindingResult(false, "Enter the binding code generated by the website.");
        }

        try {
            var pluginVersion = Assembly.GetExecutingAssembly().GetName().Version?.ToString() ?? "0.0.0.0";
            var requestBody = JsonSerializer.Serialize(new {
                code,
                pluginVersion,
                gameVersion = GetCurrentGameVersion(),
                clientBuildHash = CloudUploadProtocol.GetClientBuildHash(),
            });
            using var request = new HttpRequestMessage(HttpMethod.Post, endpoint) {
                Content = new StringContent(requestBody, Encoding.UTF8, "application/json"),
            };
            using var response = await _httpClient.SendAsync(request, HttpCompletionOption.ResponseContentRead, cancellationToken);
            if(!response.IsSuccessStatusCode) {
                _plugin.Log.Warning($"Plugin binding was rejected with HTTP {(int)response.StatusCode}.");
                return new CloudBindingResult(false, response.StatusCode == HttpStatusCode.UnprocessableEntity ? "The binding code is invalid, expired, or already used." : "The binding service rejected the request.");
            }

            var body = await response.Content.ReadAsStringAsync(cancellationToken);
            var result = JsonSerializer.Deserialize<CloudBindingResponse>(body, new JsonSerializerOptions { PropertyNameCaseInsensitive = true });
            if(result == null || string.IsNullOrWhiteSpace(result.InstallationId) || string.IsNullOrWhiteSpace(result.AccountId) || result.KeyVersion <= 0) {
                return new CloudBindingResult(false, "The server returned incomplete binding credentials.");
            }
            var secret = Convert.FromBase64String(result.Secret);
            if(secret.Length < 32) {
                return new CloudBindingResult(false, "The server returned an invalid binding secret.");
            }
            SetCredentials(result.InstallationId, result.AccountId, result.KeyVersion.ToString(), secret);
            return new CloudBindingResult(true, "Plugin binding succeeded.");
        } catch(OperationCanceledException) when(cancellationToken.IsCancellationRequested) {
            return new CloudBindingResult(false, "Binding was cancelled.");
        } catch(Exception ex) {
            _plugin.Log.Warning(ex, "Plugin binding failed.");
            return new CloudBindingResult(false, "Unable to reach the binding service. Try again later.");
        }
    }

    internal void ClearCredentials() {
        _plugin.Configuration.CloudUploadEnabled = false;
        _plugin.Configuration.CloudUploadInstallationId = "";
        _plugin.Configuration.CloudUploadAccountId = "";
        _plugin.Configuration.CloudUploadKeyVersion = "";
        _plugin.Configuration.CloudUploadProtectedSecret = "";
        _plugin.Configuration.Save();
        _reportedNotReady = false;
    }

    private async Task RunAsync() {
        try {
            await foreach(var pending in _queue.Reader.ReadAllAsync(_shutdown.Token)) {
                await UploadWithRetryAsync(pending, _shutdown.Token);
            }
        } catch(OperationCanceledException) when(_shutdown.IsCancellationRequested) {
        } catch(Exception ex) {
            _plugin.Log.Error(ex, "Cloud upload worker stopped unexpectedly.");
        }
    }

    private async Task UploadWithRetryAsync(PendingUpload pending, CancellationToken cancellationToken) {
        int[] retryDelaysSeconds = [0, 2, 10];
        string? lastError = null;
        for(var attempt = 0; attempt < retryDelaysSeconds.Length; attempt++) {
            if(retryDelaysSeconds[attempt] > 0) {
                await Task.Delay(TimeSpan.FromSeconds(retryDelaysSeconds[attempt]), cancellationToken);
            }

            try {
                if(!TryGetEndpoint(out var endpoint) || !TryGetCredentials(out var credentials)) {
                    return;
                }
                await RecordAttemptAsync(pending.SourceMatchId);
                using var request = CreateRequest(endpoint, credentials, pending);
                using var response = await _httpClient.SendAsync(request, HttpCompletionOption.ResponseHeadersRead, cancellationToken);
                if(response.IsSuccessStatusCode || response.StatusCode == HttpStatusCode.Conflict) {
                    await RecordUploadedAsync(pending.SourceMatchId);
                    _plugin.Log.Information($"Uploaded Frontline match {pending.SourceMatchId}.");
                    return;
                }
                if((int)response.StatusCode is >= 400 and < 500 && response.StatusCode != HttpStatusCode.TooManyRequests) {
                    lastError = $"HTTP {(int)response.StatusCode}";
                    await RecordFailedAsync(pending.SourceMatchId, lastError);
                    _plugin.Log.Warning($"Cloud upload rejected Frontline match {pending.SourceMatchId}: {lastError}.");
                    return;
                }
                lastError = $"HTTP {(int)response.StatusCode}";
                _plugin.Log.Warning($"Cloud upload attempt {attempt + 1} failed for {pending.SourceMatchId}: HTTP {(int)response.StatusCode}.");
            } catch(OperationCanceledException) when(cancellationToken.IsCancellationRequested) {
                return;
            } catch(Exception ex) {
                lastError = $"{ex.GetType().Name}: {ex.Message}";
                _plugin.Log.Warning(ex, $"Cloud upload attempt {attempt + 1} failed for {pending.SourceMatchId}.");
            }
        }
        await RecordFailedAsync(pending.SourceMatchId, lastError ?? "Upload attempts exhausted.");
    }

    private async Task RecordAttemptAsync(string sourceMatchId) {
        var record = _plugin.Storage.GetCloudUploads().FindById(sourceMatchId);
        if(record == null) return;
        record.AttemptCount++;
        record.LastAttemptAt = DateTime.UtcNow;
        await _plugin.Storage.UpsertCloudUpload(record);
    }

    private async Task RecordUploadedAsync(string sourceMatchId) {
        var record = _plugin.Storage.GetCloudUploads().FindById(sourceMatchId);
        if(record == null) return;
        record.Status = CloudUploadStatus.Uploaded;
        record.UploadedAt = DateTime.UtcNow;
        record.LastError = null;
        await _plugin.Storage.UpsertCloudUpload(record);
    }

    private async Task RecordFailedAsync(string sourceMatchId, string error) {
        var record = _plugin.Storage.GetCloudUploads().FindById(sourceMatchId);
        if(record == null) return;
        record.Status = CloudUploadStatus.Failed;
        record.LastError = error.Length <= 500 ? error : error[..500];
        await _plugin.Storage.UpsertCloudUpload(record);
    }

    private static HttpRequestMessage CreateRequest(Uri endpoint, UploadCredentials credentials, PendingUpload pending) {
        var nonce = Guid.NewGuid().ToString();
        var signed = CloudUploadProtocol.Sign(pending.Body, credentials, pending.PluginVersion, pending.BuildHash, DateTimeOffset.UtcNow, nonce, pending.IdempotencyKey);
        var request = new HttpRequestMessage(HttpMethod.Post, endpoint) {
            Content = new ByteArrayContent(pending.Body),
        };
        request.Content.Headers.ContentType = new MediaTypeHeaderValue("application/json");
        request.Content.Headers.ContentEncoding.Add("gzip");
        AddSignedHeaders(request, credentials, signed, nonce, pending.PluginVersion, pending.BuildHash, pending.IdempotencyKey);
        return request;
    }

    private static void AddSignedHeaders(HttpRequestMessage request, UploadCredentials credentials, SignedUploadRequest signed, string nonce, string pluginVersion, string buildHash, string idempotencyKey) {
        request.Headers.TryAddWithoutValidation("X-PvPLogs-Installation", credentials.InstallationId);
        request.Headers.TryAddWithoutValidation("X-PvPLogs-Account", credentials.AccountId);
        request.Headers.TryAddWithoutValidation("X-PvPLogs-Key-Version", credentials.KeyVersion);
        request.Headers.TryAddWithoutValidation("X-PvPLogs-Timestamp", signed.Timestamp);
        request.Headers.TryAddWithoutValidation("X-PvPLogs-Nonce", nonce);
        request.Headers.TryAddWithoutValidation("X-PvPLogs-Plugin-Version", pluginVersion);
        request.Headers.TryAddWithoutValidation("X-PvPLogs-Schema-Version", CloudUploadProtocol.SchemaVersion.ToString());
        request.Headers.TryAddWithoutValidation("X-PvPLogs-Client-Build", buildHash);
        request.Headers.TryAddWithoutValidation("X-PvPLogs-Content-SHA256", signed.BodySha256);
        request.Headers.TryAddWithoutValidation("X-PvPLogs-Signature", signed.Signature);
        request.Headers.TryAddWithoutValidation("Idempotency-Key", idempotencyKey);
    }

    private bool TryGetCredentials(out UploadCredentials credentials) {
        credentials = null!;
        var config = _plugin.Configuration;
        if(string.IsNullOrWhiteSpace(config.CloudUploadInstallationId)
            || string.IsNullOrWhiteSpace(config.CloudUploadAccountId)
            || string.IsNullOrWhiteSpace(config.CloudUploadKeyVersion)
            || string.IsNullOrWhiteSpace(config.CloudUploadProtectedSecret)) {
            return false;
        }
        try {
            var secret = CloudCredentialProtector.Unprotect(config.CloudUploadProtectedSecret);
            if(secret.Length < 32) {
                return false;
            }
            credentials = new UploadCredentials(config.CloudUploadInstallationId, config.CloudUploadAccountId, config.CloudUploadKeyVersion, secret);
            return true;
        } catch(Exception ex) {
            _plugin.Log.Warning(ex, "Unable to unlock the cloud upload credential for the current Windows user.");
            return false;
        }
    }

    private bool TryGetEndpoint(out Uri endpoint) {
        return TryGetApiEndpoint(CloudUploadProtocol.UploadPath, out endpoint);
    }

    private bool TryGetApiEndpoint(string path, out Uri endpoint) {
        endpoint = null!;
        if(!Uri.TryCreate(_plugin.Configuration.CloudUploadApiBaseUrl, UriKind.Absolute, out var baseUri)) {
            return false;
        }
        if(baseUri.Scheme != Uri.UriSchemeHttps && !(baseUri.Scheme == Uri.UriSchemeHttp && baseUri.IsLoopback)) {
            return false;
        }
        endpoint = new Uri(baseUri, path);
        return true;
    }

    private static unsafe string GetCurrentGameVersion() {
        var framework = FFXIVClientStructs.FFXIV.Client.System.Framework.Framework.Instance();
        return framework != null ? framework->GameVersionString : "unknown";
    }

    public void Dispose() {
        _queue.Writer.TryComplete();
        _shutdown.Cancel();
        try {
            _worker.Wait(TimeSpan.FromSeconds(2));
        } catch(AggregateException) {
        }
        _shutdown.Dispose();
        _httpClient.Dispose();
    }

    private sealed record PendingUpload(byte[] Body, string PluginVersion, string BuildHash, string IdempotencyKey, string SourceMatchId);
    private sealed class CloudBindingResponse {
        public string InstallationId { get; init; } = "";
        public string AccountId { get; init; } = "";
        public int KeyVersion { get; init; }
        public string Secret { get; init; } = "";
    }
}

internal sealed record CloudBindingResult(bool Success, string Message);
