using Lumina.Excel.Sheets;
using PvpStats.Types.Match;
using PvpStats.Types.Match.Timeline;
using PvpStats.Types.Player;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;

namespace PvpStats.Services.Cloud;

internal sealed class RivalWingsUploadMapper {
    private readonly Plugin _plugin;
    internal RivalWingsUploadMapper(Plugin plugin)=>_plugin=plugin;

    internal UploadEnvelopeV1 Map(RivalWingsMatch match,RivalWingsMatchTimeline? timeline=null) {
        if(!match.IsCompleted||match.MatchStartTime==null||match.MatchEndTime==null||match.Arena==null||match.MatchWinner==null||match.Players==null||match.PlayerScoreboards==null||match.StructureHealth==null)throw new InvalidOperationException("Only completed Rival Wings matches can be uploaded.");
        var worlds=Worlds();var pluginVersion=match.PluginVersion??Assembly.GetExecutingAssembly().GetName().Version?.ToString()??"0.0.0.0";var gameVersion=Required(match.GameVersion,"game version");var observedAt=Utc(match.MatchEndTime.Value);
        var players=match.Players.Select(player=>MapPlayer(match,player,worlds)).ToList();var observations=match.Players.Where(player=>player.ContentId is >0).Select(player=>MapObservation(player,worlds,observedAt)).ToList();
        return new UploadEnvelopeV1{ExportedAt=DateTime.UtcNow,Client=new(){PluginVersion=pluginVersion,GameVersion=gameVersion,BuildHash=CloudUploadProtocol.GetClientBuildHash(),DataCenter=Optional(match.DataCenter)},Matches=[],RivalWingsMatches=[new(){SourceMatchId=match.Id.ToString(),SourceVersion=match.Version,IsCompleted=true,ValidationFlags=(ulong)match.Flags,DutyStartTime=Utc(match.DutyStartTime),MatchStartTime=Utc(match.MatchStartTime.Value),MatchEndTime=Utc(match.MatchEndTime.Value),DutyId=match.DutyId,TerritoryId=match.TerritoryId,Arena=Arena(match.Arena.Value),Winner=Team(match.MatchWinner.Value),DataCenter=Optional(match.DataCenter),GameVersion=gameVersion,PluginVersion=pluginVersion,PlayerCount=match.PlayerCount,LocalPlayer=match.LocalPlayer==null?null:Alias(match.LocalPlayer,worlds),Players=players,Teams=[MapTeam(match,RivalWingsTeamName.Falcons),MapTeam(match,RivalWingsTeamName.Ravens)],Timeline=Timeline(timeline,match.MatchStartTime.Value,match.MatchEndTime.Value)}],IdentityObservations=observations.Count==0?null:observations};
    }
    private RivalWingsParticipantV1 MapPlayer(RivalWingsMatch match,RivalWingsPlayer player,IReadOnlyDictionary<string,uint> worlds){if(player.Job==null||player.ClassJobId is null or 0)throw new InvalidOperationException($"Player {player.Name} is missing job data.");if(!match.PlayerScoreboards!.TryGetValue(player.Name,out var score))throw new InvalidOperationException($"Player {player.Name} is missing a scoreboard.");Dictionary<string,long>? mechs=null;if(match.PlayerMechTime?.TryGetValue(player.Name,out var values)==true)mechs=values.ToDictionary(v=>Mech(v.Key),v=>checked((long)Math.Round(v.Value*1000)));return new(){Alias=Alias(player.Name,worlds),AccountId=Id(player.AccountId),ContentId=Id(player.ContentId),Job=player.Job.Value.ToString(),ClassJobId=player.ClassJobId.Value,Team=Team(player.Team),Alliance=player.Alliance,Scoreboard=new(){Kills=score.Kills,Deaths=score.Deaths,Assists=score.Assists,DamageDealt=score.DamageDealt,DamageToOther=score.DamageToOther,DamageTaken=score.DamageTaken,HpRestored=score.HPRestored,Ceruleum=score.Ceruleum,Special1=score.Special1},MechTimeMillis=mechs};}
    private RivalWingsTeamV1 MapTeam(RivalWingsMatch match,RivalWingsTeamName team){var structures=match.StructureHealth![team].ToDictionary(v=>Structure(v.Key),v=>(long)v.Value);Dictionary<string,long>? mechs=null;if(match.TeamMechTime?.TryGetValue(team,out var mechValues)==true)mechs=mechValues.ToDictionary(v=>Mech(v.Key),v=>checked((long)Math.Round(v.Value*1000)));Dictionary<string,long>? supplies=null;if(match.Supplies?.TryGetValue(team,out var supplyValues)==true)supplies=supplyValues.ToDictionary(v=>Supply(v.Key),v=>(long)v.Value);return new(){Team=Team(team),Placement=match.MatchWinner==team?1:2,StructureHp=structures,MechTimeMillis=mechs,Supplies=supplies,Mercenaries=match.Mercs?.GetValueOrDefault(team)??0};}
    private IdentityObservationV1 MapObservation(RivalWingsPlayer player,IReadOnlyDictionary<string,uint> worlds,DateTime observedAt){var linked=_plugin.PlayerLinksService.GetAllLinkedAliases(player.Name).Where(v=>!v.Equals(player.Name)).Distinct().Select(v=>Alias(v,worlds)).ToList();return new(){AccountId=Id(player.AccountId),ContentId=player.ContentId!.Value.ToString(),CurrentAlias=Alias(player.Name,worlds),LinkedAliases=linked.Count==0?null:linked,Source=linked.Count==0?"pvp_result":"usedname",ObservedAt=observedAt};}
    private static RivalWingsTimelineV1? Timeline(RivalWingsMatchTimeline? source,DateTime start,DateTime end){if(source==null)return null;var min=Utc(start).AddMinutes(-1);var max=Utc(end).AddMinutes(1);bool In(DateTime value)=>Utc(value)>=min&&Utc(value)<=max;var structures=(source.StructureHealths??[]).SelectMany(team=>team.Value.SelectMany(structure=>structure.Value.Where(e=>In(e.Timestamp)).Select(e=>new RivalWingsStructureEventV1{Timestamp=Utc(e.Timestamp),Team=Team(team.Key),Structure=Structure(structure.Key),Health=e.Health}))).OrderBy(e=>e.Timestamp).ToList();var mechs=(source.MechCounts??[]).SelectMany(team=>team.Value.SelectMany(mech=>mech.Value.Where(e=>In(e.Timestamp)).Select(e=>new RivalWingsMechEventV1{Timestamp=Utc(e.Timestamp),Team=Team(team.Key),Mech=Mech(mech.Key),Count=e.Count}))).OrderBy(e=>e.Timestamp).ToList();var soaring=(source.AllianceStacks??[]).SelectMany(pair=>pair.Value.Where(e=>In(e.Timestamp)).Select(e=>new RivalWingsSoaringEventV1{Timestamp=Utc(e.Timestamp),Team=Team(e.Team??(RivalWingsTeamName)(pair.Key/6)),Alliance=e.Alliance??pair.Key%6,Stacks=e.Count})).OrderBy(e=>e.Timestamp).ToList();var claims=(source.MercClaims??[]).Where(e=>In(e.Timestamp)).Select(e=>new RivalWingsClaimEventV1{Timestamp=Utc(e.Timestamp),Team=Team(e.Team),Kind="mercenary"}).Concat((source.MidClaims??[]).Where(e=>In(e.Timestamp)).Select(e=>new RivalWingsClaimEventV1{Timestamp=Utc(e.Timestamp),Team=Team(e.Team),Kind="resource",Resource=Supply(e.Kind)})).OrderBy(e=>e.Timestamp).ToList();if(structures.Count==0&&mechs.Count==0&&soaring.Count==0&&claims.Count==0)return null;return new(){StructureHealth=structures.Count==0?null:structures,MechCounts=mechs.Count==0?null:mechs,Soaring=soaring.Count==0?null:soaring,Claims=claims.Count==0?null:claims};}
    private Dictionary<string,uint> Worlds()=>_plugin.DataManager.GetExcelSheet<World>().GroupBy(w=>w.Name.ToString(),StringComparer.OrdinalIgnoreCase).ToDictionary(g=>g.Key,g=>g.First().RowId,StringComparer.OrdinalIgnoreCase);
    private static UploadAliasV1 Alias(PlayerAlias value,IReadOnlyDictionary<string,uint> worlds){if(!worlds.TryGetValue(value.HomeWorld,out var id)||id==0)throw new InvalidOperationException($"Unable to resolve home world ID for {value}.");return new(){Name=Required(value.Name,"player name"),HomeWorld=Required(value.HomeWorld,"home world"),HomeWorldId=id};}
    private static string Team(RivalWingsTeamName value)=>value switch{RivalWingsTeamName.Falcons=>"falcons",RivalWingsTeamName.Ravens=>"ravens",_=>throw new InvalidOperationException("Unsupported RW team")};private static string Arena(RivalWingsMap value)=>value switch{RivalWingsMap.Astragalos=>"astragalos",RivalWingsMap.HiddenGorge=>"hidden_gorge",_=>throw new InvalidOperationException("Unsupported RW arena")};private static string Mech(RivalWingsMech value)=>value switch{RivalWingsMech.Chaser=>"chaser",RivalWingsMech.Oppressor=>"oppressor",RivalWingsMech.Justice=>"justice",_=>throw new InvalidOperationException("Unsupported mech")};private static string Structure(RivalWingsStructure value)=>value switch{RivalWingsStructure.Core=>"core",RivalWingsStructure.Tower1=>"tower_1",RivalWingsStructure.Tower2=>"tower_2",_=>throw new InvalidOperationException("Unsupported structure")};private static string Supply(RivalWingsSupplies value)=>value switch{RivalWingsSupplies.Gobtank=>"gobtank",RivalWingsSupplies.Ceruleum=>"ceruleum",RivalWingsSupplies.Gobbiejuice=>"gobbiejuice",RivalWingsSupplies.Gobcrate=>"gobcrate",_=>throw new InvalidOperationException("Unsupported supply")};
    private static string? Id(ulong? value)=>value is >0?value.Value.ToString():null;private static string Required(string? value,string field)=>!string.IsNullOrWhiteSpace(value)?value:throw new InvalidOperationException($"Missing {field}.");private static string? Optional(string? value)=>string.IsNullOrWhiteSpace(value)?null:value;private static DateTime Utc(DateTime value)=>value.Kind==DateTimeKind.Utc?value:value.ToUniversalTime();
}
